// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrmbDRt70ioUvEpNnJBGdCzAH03FIg3a4',
    appId: '1:1089601481748:web:c48391c197aaff01ee0b01',
    messagingSenderId: '1089601481748',
    projectId: 'easy-ride-flutter-app',
    authDomain: 'easy-ride-flutter-app.firebaseapp.com',
    storageBucket: 'easy-ride-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9hyP5S2HcSvmKsa-TNLl2VvwjcTPu3rw',
    appId: '1:1089601481748:android:bc0b96cbe3ebc8d1ee0b01',
    messagingSenderId: '1089601481748',
    projectId: 'easy-ride-flutter-app',
    storageBucket: 'easy-ride-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArH2ASI6YyKArSOWv674a5iMDoVrrzwkc',
    appId: '1:1089601481748:ios:413868044397e0aeee0b01',
    messagingSenderId: '1089601481748',
    projectId: 'easy-ride-flutter-app',
    storageBucket: 'easy-ride-flutter-app.appspot.com',
    iosBundleId: 'com.example.easyRide',
  );
}
